# Generated by Django 2.2.5 on 2019-11-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='userrating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
