# Generated by Django 2.2.5 on 2019-11-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rating_userrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('long_url', models.URLField(primary_key=True, serialize=False)),
                ('short_url', models.URLField(default='')),
                ('image', models.FileField(upload_to='images/barcodes/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at']},
        ),
    ]
